#ifndef EE_X86_INSTRUCTION_PSEUDONYMS_IG
#define EE_X86_INSTRUCTION_PSEUDONYMS_IG

#ifndef EE_PRV_UNLOCK_DETAIL
#error "Direct inclusion of detail headers is forbidden."
#endif

#include "ee/ee_x86.h"

extern const ee_x86_instruction_type_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPPS[];
extern const ee_size_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPPS_COUNT;

extern const ee_x86_instruction_type_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPPD[];
extern const ee_size_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPPD_COUNT;

extern const ee_x86_instruction_type_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPSD[];
extern const ee_size_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPSD_COUNT;

extern const ee_x86_instruction_type_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPSS[];
extern const ee_size_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPSS_COUNT;

extern const ee_x86_instruction_type_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPPS[];
extern const ee_size_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPPS_COUNT;

extern const ee_x86_instruction_type_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPPD[];
extern const ee_size_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPPD_COUNT;

extern const ee_x86_instruction_type_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPSD[];
extern const ee_size_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPSD_COUNT;

extern const ee_x86_instruction_type_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPSS[];
extern const ee_size_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPSS_COUNT;

#endif
