#ifndef EE_X86_INSTRUCTION_PSEUDONYMS_IMPL_IG
#define EE_X86_INSTRUCTION_PSEUDONYMS_IMPL_IG

#ifndef EE_PRV_UNLOCK_DETAIL
#error "Direct inclusion of detail headers is forbidden."
#endif

#include "ee/detail/x86/instruction_pseudonyms.h"

const ee_x86_instruction_type_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPPS[] = {
    EE_X86_INSTRUCTION_CMPEQPS,
    EE_X86_INSTRUCTION_CMPLTPS,
    EE_X86_INSTRUCTION_CMPLEPS,
    EE_X86_INSTRUCTION_CMPUNORDPS,
    EE_X86_INSTRUCTION_CMPNEQPS,
    EE_X86_INSTRUCTION_CMPNLTPS,
    EE_X86_INSTRUCTION_CMPNLEPS,
    EE_X86_INSTRUCTION_CMPORDPS
};

const ee_size_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPPS_COUNT = EE_GET_ARRAY_LEN(EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPPS);

const ee_x86_instruction_type_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPPD[] = {
    EE_X86_INSTRUCTION_CMPEQPD,
    EE_X86_INSTRUCTION_CMPLTPD,
    EE_X86_INSTRUCTION_CMPLEPD,
    EE_X86_INSTRUCTION_CMPUNORDPD,
    EE_X86_INSTRUCTION_CMPNEQPD,
    EE_X86_INSTRUCTION_CMPNLTPD,
    EE_X86_INSTRUCTION_CMPNLEPD,
    EE_X86_INSTRUCTION_CMPORDPD
};

const ee_size_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPPD_COUNT = EE_GET_ARRAY_LEN(EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPPD);

const ee_x86_instruction_type_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPSD[] = {
    EE_X86_INSTRUCTION_CMPEQSD,
    EE_X86_INSTRUCTION_CMPLTSD,
    EE_X86_INSTRUCTION_CMPLESD,
    EE_X86_INSTRUCTION_CMPUNORDSD,
    EE_X86_INSTRUCTION_CMPNEQSD,
    EE_X86_INSTRUCTION_CMPNLTSD,
    EE_X86_INSTRUCTION_CMPNLESD,
    EE_X86_INSTRUCTION_CMPORDSD
};

const ee_size_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPSD_COUNT = EE_GET_ARRAY_LEN(EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPSD);

const ee_x86_instruction_type_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPSS[] = {
    EE_X86_INSTRUCTION_CMPEQSS,
    EE_X86_INSTRUCTION_CMPLTSS,
    EE_X86_INSTRUCTION_CMPLESS,
    EE_X86_INSTRUCTION_CMPUNORDSS,
    EE_X86_INSTRUCTION_CMPNEQSS,
    EE_X86_INSTRUCTION_CMPNLTSS,
    EE_X86_INSTRUCTION_CMPNLESS,
    EE_X86_INSTRUCTION_CMPORDSS
};

const ee_size_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPSS_COUNT = EE_GET_ARRAY_LEN(EE_PRV_X86_INSTRUCTION_PSEUDONYMS_CMPSS);

const ee_x86_instruction_type_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPPS[] = {
    EE_X86_INSTRUCTION_VCMPEQPS,
    EE_X86_INSTRUCTION_VCMPLTPS,
    EE_X86_INSTRUCTION_VCMPLEPS,
    EE_X86_INSTRUCTION_VCMPUNORDPS,
    EE_X86_INSTRUCTION_VCMPNEQPS,
    EE_X86_INSTRUCTION_VCMPNLTPS,
    EE_X86_INSTRUCTION_VCMPNLEPS,
    EE_X86_INSTRUCTION_VCMPORDPS,
    EE_X86_INSTRUCTION_VCMPEQ_UQPS,
    EE_X86_INSTRUCTION_VCMPNGEPS,
    EE_X86_INSTRUCTION_VCMPNGTPS,
    EE_X86_INSTRUCTION_VCMPFALSEPS,
    EE_X86_INSTRUCTION_VCMPNEQ_OQPS,
    EE_X86_INSTRUCTION_VCMPGEPS,
    EE_X86_INSTRUCTION_VCMPGTPS,
    EE_X86_INSTRUCTION_VCMPTRUEPS,
    EE_X86_INSTRUCTION_VCMPEQ_OSPS,
    EE_X86_INSTRUCTION_VCMPLT_OQPS,
    EE_X86_INSTRUCTION_VCMPLE_OQPS,
    EE_X86_INSTRUCTION_VCMPUNORD_SPS,
    EE_X86_INSTRUCTION_VCMPNEQ_USPS,
    EE_X86_INSTRUCTION_VCMPNLT_UQPS,
    EE_X86_INSTRUCTION_VCMPNLE_UQPS,
    EE_X86_INSTRUCTION_VCMPORD_SPS,
    EE_X86_INSTRUCTION_VCMPEQ_USPS,
    EE_X86_INSTRUCTION_VCMPNGE_UQPS,
    EE_X86_INSTRUCTION_VCMPNGT_UQPS,
    EE_X86_INSTRUCTION_VCMPFALSE_OSPS,
    EE_X86_INSTRUCTION_VCMPNEQ_OSPS,
    EE_X86_INSTRUCTION_VCMPGE_OQPS,
    EE_X86_INSTRUCTION_VCMPGT_OQPS,
    EE_X86_INSTRUCTION_VCMPTRUE_USPS
};

const ee_size_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPPS_COUNT = EE_GET_ARRAY_LEN(EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPPS);

const ee_x86_instruction_type_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPPD[] = {
    EE_X86_INSTRUCTION_VCMPEQPD,
    EE_X86_INSTRUCTION_VCMPLTPD,
    EE_X86_INSTRUCTION_VCMPLEPD,
    EE_X86_INSTRUCTION_VCMPUNORDPD,
    EE_X86_INSTRUCTION_VCMPNEQPD,
    EE_X86_INSTRUCTION_VCMPNLTPD,
    EE_X86_INSTRUCTION_VCMPNLEPD,
    EE_X86_INSTRUCTION_VCMPORDPD,
    EE_X86_INSTRUCTION_VCMPEQ_UQPD,
    EE_X86_INSTRUCTION_VCMPNGEPD,
    EE_X86_INSTRUCTION_VCMPNGTPD,
    EE_X86_INSTRUCTION_VCMPFALSEPD,
    EE_X86_INSTRUCTION_VCMPNEQ_OQPD,
    EE_X86_INSTRUCTION_VCMPGEPD,
    EE_X86_INSTRUCTION_VCMPGTPD,
    EE_X86_INSTRUCTION_VCMPTRUEPD,
    EE_X86_INSTRUCTION_VCMPEQ_OSPD,
    EE_X86_INSTRUCTION_VCMPLT_OQPD,
    EE_X86_INSTRUCTION_VCMPLE_OQPD,
    EE_X86_INSTRUCTION_VCMPUNORD_SPD,
    EE_X86_INSTRUCTION_VCMPNEQ_USPD,
    EE_X86_INSTRUCTION_VCMPNLT_UQPD,
    EE_X86_INSTRUCTION_VCMPNLE_UQPD,
    EE_X86_INSTRUCTION_VCMPORD_SPD,
    EE_X86_INSTRUCTION_VCMPEQ_USPD,
    EE_X86_INSTRUCTION_VCMPNGE_UQPD,
    EE_X86_INSTRUCTION_VCMPNGT_UQPD,
    EE_X86_INSTRUCTION_VCMPFALSE_OSPD,
    EE_X86_INSTRUCTION_VCMPNEQ_OSPD,
    EE_X86_INSTRUCTION_VCMPGE_OQPD,
    EE_X86_INSTRUCTION_VCMPGT_OQPD,
    EE_X86_INSTRUCTION_VCMPTRUE_USPD
};

const ee_size_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPPD_COUNT = EE_GET_ARRAY_LEN(EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPPD);

const ee_x86_instruction_type_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPSD[] = {
    EE_X86_INSTRUCTION_VCMPEQSD,
    EE_X86_INSTRUCTION_VCMPLTSD,
    EE_X86_INSTRUCTION_VCMPLESD,
    EE_X86_INSTRUCTION_VCMPUNORDSD,
    EE_X86_INSTRUCTION_VCMPNEQSD,
    EE_X86_INSTRUCTION_VCMPNLTSD,
    EE_X86_INSTRUCTION_VCMPNLESD,
    EE_X86_INSTRUCTION_VCMPORDSD,
    EE_X86_INSTRUCTION_VCMPEQ_UQSD,
    EE_X86_INSTRUCTION_VCMPNGESD,
    EE_X86_INSTRUCTION_VCMPNGTSD,
    EE_X86_INSTRUCTION_VCMPFALSESD,
    EE_X86_INSTRUCTION_VCMPNEQ_OQSD,
    EE_X86_INSTRUCTION_VCMPGESD,
    EE_X86_INSTRUCTION_VCMPGTSD,
    EE_X86_INSTRUCTION_VCMPTRUESD,
    EE_X86_INSTRUCTION_VCMPEQ_OSSD,
    EE_X86_INSTRUCTION_VCMPLT_OQSD,
    EE_X86_INSTRUCTION_VCMPLE_OQSD,
    EE_X86_INSTRUCTION_VCMPUNORD_SSD,
    EE_X86_INSTRUCTION_VCMPNEQ_USSD,
    EE_X86_INSTRUCTION_VCMPNLT_UQSD,
    EE_X86_INSTRUCTION_VCMPNLE_UQSD,
    EE_X86_INSTRUCTION_VCMPORD_SSD,
    EE_X86_INSTRUCTION_VCMPEQ_USSD,
    EE_X86_INSTRUCTION_VCMPNGE_UQSD,
    EE_X86_INSTRUCTION_VCMPNGT_UQSD,
    EE_X86_INSTRUCTION_VCMPFALSE_OSSD,
    EE_X86_INSTRUCTION_VCMPNEQ_OSSD,
    EE_X86_INSTRUCTION_VCMPGE_OQSD,
    EE_X86_INSTRUCTION_VCMPGT_OQSD,
    EE_X86_INSTRUCTION_VCMPTRUE_USSD
};

const ee_size_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPSD_COUNT = EE_GET_ARRAY_LEN(EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPSD);

const ee_x86_instruction_type_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPSS[] = {
    EE_X86_INSTRUCTION_VCMPEQSS,
    EE_X86_INSTRUCTION_VCMPLTSS,
    EE_X86_INSTRUCTION_VCMPLESS,
    EE_X86_INSTRUCTION_VCMPUNORDSS,
    EE_X86_INSTRUCTION_VCMPNEQSS,
    EE_X86_INSTRUCTION_VCMPNLTSS,
    EE_X86_INSTRUCTION_VCMPNLESS,
    EE_X86_INSTRUCTION_VCMPORDSS,
    EE_X86_INSTRUCTION_VCMPEQ_UQSS,
    EE_X86_INSTRUCTION_VCMPNGESS,
    EE_X86_INSTRUCTION_VCMPNGTSS,
    EE_X86_INSTRUCTION_VCMPFALSESS,
    EE_X86_INSTRUCTION_VCMPNEQ_OQSS,
    EE_X86_INSTRUCTION_VCMPGESS,
    EE_X86_INSTRUCTION_VCMPGTSS,
    EE_X86_INSTRUCTION_VCMPTRUESS,
    EE_X86_INSTRUCTION_VCMPEQ_OSSS,
    EE_X86_INSTRUCTION_VCMPLT_OQSS,
    EE_X86_INSTRUCTION_VCMPLE_OQSS,
    EE_X86_INSTRUCTION_VCMPUNORD_SSS,
    EE_X86_INSTRUCTION_VCMPNEQ_USSS,
    EE_X86_INSTRUCTION_VCMPNLT_UQSS,
    EE_X86_INSTRUCTION_VCMPNLE_UQSS,
    EE_X86_INSTRUCTION_VCMPORD_SSS,
    EE_X86_INSTRUCTION_VCMPEQ_USSS,
    EE_X86_INSTRUCTION_VCMPNGE_UQSS,
    EE_X86_INSTRUCTION_VCMPNGT_UQSS,
    EE_X86_INSTRUCTION_VCMPFALSE_OSSS,
    EE_X86_INSTRUCTION_VCMPNEQ_OSSS,
    EE_X86_INSTRUCTION_VCMPGE_OQSS,
    EE_X86_INSTRUCTION_VCMPGT_OQSS,
    EE_X86_INSTRUCTION_VCMPTRUE_USSS
};

const ee_size_t EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPSS_COUNT = EE_GET_ARRAY_LEN(EE_PRV_X86_INSTRUCTION_PSEUDONYMS_VCMPSS);

#endif
