#ifndef EE_X86_OPERAND_CONSTRAINTS_IG
#define EE_X86_OPERAND_CONSTRAINTS_IG

#ifndef EE_PRV_UNLOCK_DETAIL
#error "Direct inclusion of detail headers is forbidden."
#endif

#include "ee/ee_base.h"

/* Types
*/

typedef enum {

    EE_PRV_X86_OPDFAM_NULL,
    EE_PRV_X86_OPDFAM_MODRM,
    EE_PRV_X86_OPDFAM_MODRM_BITS,
    EE_PRV_X86_OPDFAM_BYTE_RANGE

} ee_prv_x86_operand_family_t;

typedef struct {

    ee_prv_x86_operand_family_t family;

} ee_prv_x86_operand_constraints_t;

typedef struct {

    ee_prv_x86_operand_constraints_t hdr;
    ee_int16_t mandatory_mod;
    ee_int16_t mandatory_rm;
    ee_int16_t mandatory_reg;
    ee_int16_t prohibited_mod;
    ee_int16_t prohibited_rm;
    ee_int16_t prohibited_reg;

} ee_prv_x86_modrm_operand_constraints_t;

typedef struct {

    ee_prv_x86_operand_constraints_t hdr;
    ee_int16_t mandatory_mod_bit_comb;
    ee_int16_t mandatory_rm_bit_comb;
    ee_int16_t mandatory_reg_bit_comb;
    ee_int16_t prohibited_mod_bit_comb;
    ee_int16_t prohibited_rm_bit_comb;
    ee_int16_t prohibited_reg_bit_comb;

} ee_prv_x86_modrm_operand_bit_constraints_t;

typedef struct {

    ee_prv_x86_operand_constraints_t hdr;
    ee_byte_t first;
    ee_byte_t last;

} ee_prv_x86_byte_range_operand_constraints_t;

/* Fields
*/

extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_ANY_M;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_ANY_R;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_MOD0;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG0;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG0M;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG0R;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG1;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG1M;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG1R;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG2;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG2M;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG2R;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG3;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG3M;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG3R;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG4;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG4M;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG4R;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG5;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG5M;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG5R;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG6;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG6M;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG6R;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG7;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG7M;
extern const ee_prv_x86_modrm_operand_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG7R;

extern const ee_prv_x86_modrm_operand_bit_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG0XX_M;
extern const ee_prv_x86_modrm_operand_bit_constraints_t EE_PRV_X86_OPRDCONS_MODRM_REG0XX_RM0XX_R;

extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_0A;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_C1;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_C2;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_C3;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_C4;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_C5;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_C8;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_C9;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_CC;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_CD;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_CE;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_CF;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_D0;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_D1;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_D4;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_D5;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_D6;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_D7;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_D8;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_D9;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_DA;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_DB;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_DC;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_DD;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_DE;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_DF;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_E0;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_E1;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_E2;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_E3;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_E4;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_E5;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_E8;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_E9;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_EA;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_EB;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_EC;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_ED;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_EE;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_EF;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_F0;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_F1;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_F2;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_F3;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_F4;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_F5;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_F6;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_F7;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_F8;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_F9;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_FA;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_FB;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_FC;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_FD;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_FE;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_FF;

extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_C0tC7;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_C8tCF;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_D0tD7;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_D8tDF;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_E0tE7;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_E8tEF;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_F0tF7;
extern const ee_prv_x86_byte_range_operand_constraints_t EE_PRV_X86_OPRDCONS_BYTE_RANGE_F8tFF;

#endif
