#ifndef EE_X86_PREFIX_CONSTRAINTS_IG
#define EE_X86_PREFIX_CONSTRAINTS_IG

#ifndef EE_PRV_UNLOCK_DETAIL
#error "Direct inclusion of detail headers is forbidden."
#endif

#include "ee/ee_base.h"

/* Types
*/

typedef enum {

    EE_PRV_X86_PREFAM_NIL,
    EE_PRV_X86_PREFAM_GRP,
    EE_PRV_X86_PREFAM_GRP_REX,
    EE_PRV_X86_PREFAM_VEX,
    EE_PRV_X86_PREFAM_ADDRESS_SIZE_OVERRIDE

} ee_prv_x86_prefix_family_t;

typedef struct {

    ee_prv_x86_prefix_family_t family;

} ee_prv_x86_prefix_constraints_t;

typedef struct {

    ee_prv_x86_prefix_constraints_t hdr;
    ee_int16_t mandatory_prefix;
    ee_int16_t prohibited_prefixes[3];

} ee_prv_x86_grp_prefix_constraints_t;

typedef struct {

    ee_prv_x86_grp_prefix_constraints_t grp_cons;
    ee_int16_t mandatory_rex_bits;
    ee_int16_t prohibited_rex_bits;

} ee_prv_x86_grp_rex_prefix_constraints_t;

typedef struct {

    ee_prv_x86_prefix_constraints_t hdr;
    ee_int16_t mandatory_l;
    ee_int16_t mandatory_pp;
    ee_int16_t mandatory_mmmmm;
    ee_int16_t mandatory_w_x86;
    ee_int16_t mandatory_w_x64;
    ee_int16_t mandatory_raw_vvvv;

} ee_prv_x86_vex_prefix_constraints_t;

typedef struct {

    ee_prv_x86_prefix_constraints_t hdr;
    ee_bool_t mandatory_for_x86;
    ee_bool_t mandatory_for_x64;
    ee_bool_t prohibited_for_x86;
    ee_bool_t prohibited_for_x64;

} ee_prv_x86_address_size_override_prefix_constraints_t;

/* Fields
*/

extern const ee_prv_x86_grp_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_NP;
extern const ee_prv_x86_grp_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_NFX;
extern const ee_prv_x86_grp_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_N66;
extern const ee_prv_x86_grp_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_NF3;
extern const ee_prv_x86_grp_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_NF2_NF3;
extern const ee_prv_x86_grp_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_66;
extern const ee_prv_x86_grp_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_66_NFX;
extern const ee_prv_x86_grp_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_F2;
extern const ee_prv_x86_grp_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_F3;

extern const ee_prv_x86_grp_rex_prefix_constraints_t EE_PRV_X86_PREFCONS_REX_W0;
extern const ee_prv_x86_grp_rex_prefix_constraints_t EE_PRV_X86_PREFCONS_REX_W1;
extern const ee_prv_x86_grp_rex_prefix_constraints_t EE_PRV_X86_PREFCONS_REX_B1;
extern const ee_prv_x86_grp_rex_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_NP_REX_W0;
extern const ee_prv_x86_grp_rex_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_NP_REX_W1;
extern const ee_prv_x86_grp_rex_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_NP_REX_B0;
extern const ee_prv_x86_grp_rex_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_N66_REX_W0;
extern const ee_prv_x86_grp_rex_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_NF3_REX_B0;
extern const ee_prv_x86_grp_rex_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_NF3_REX_B1;
extern const ee_prv_x86_grp_rex_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_66_REX_W0;
extern const ee_prv_x86_grp_rex_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_66_REX_W1;
extern const ee_prv_x86_grp_rex_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_F3_REX_W0;
extern const ee_prv_x86_grp_rex_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_F3_REX_W1;
extern const ee_prv_x86_grp_rex_prefix_constraints_t EE_PRV_X86_PREFCONS_GRP_F3_REX_B0;

extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_NP_0F;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_NP_0F_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_66_0F;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_66_0F_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_66_0F38;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_66_0F38_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_66_0F38_W0;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_66_0F38_W0_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_66_0F38_W1;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_66_0F3A;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_66_0F3A_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_66_0F3A_W0;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_66_0F3A_W0_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_F2_0F;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_F2_0F_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_F3_0F;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_F3_0F_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_NP_0F;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_NP_0F_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_NP_0F38;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F_W0xIG32;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F_W0xIG32_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F_W0xIG64;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F_W0xIG64_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F_W1;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F_W1_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F38;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F38_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F3A;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F3A_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F3A_W0;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F3A_W0_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F3A_W0xIG32;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F3A_W0xIG32_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F3A_W0xIG64;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F3A_W0xIG64_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F3A_W1;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_66_0F3A_W1_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_F2_0F3A_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_F2_0F38;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_F3_0F;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_F3_0F_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_128_F3_0F38;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_256_NP_0F;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_256_NP_0F_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_256_66_0F38_W0;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_256_66_0F38_W0_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_256_66_0F3A_W0;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_256_66_0F3A_W0_NVVVV;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_256_66_0F3A_W1;
extern const ee_prv_x86_vex_prefix_constraints_t EE_PRV_X86_PREFCONS_VEX_256_66_0F3A_W1_NVVVV;

extern const ee_prv_x86_address_size_override_prefix_constraints_t EE_PRV_X86_PREFCONS_ASO_X86;
extern const ee_prv_x86_address_size_override_prefix_constraints_t EE_PRV_X86_PREFCONS_ASO_X86N_X64;

#endif
