#ifndef EE_PE_CONSTANTS_IG
#define EE_PE_CONSTANTS_IG

#ifndef EE_PRV_UNLOCK_DETAIL
#error "Direct inclusion of detail headers is forbidden."
#endif

#define EE_PRV_PE_COUNT_OPT_HEADER_DATA_DIRS 16

#define EE_PRV_PE_SIZE_IMAGE_SIGNATURE 4
#define EE_PRV_PE_SIZE_COFF_FILE_HEADER 20
#define EE_PRV_PE_SIZE_OPTIONAL_HEADER 224
#define EE_PRV_PE_SIZE_OPTIONAL_HEADER_PLUS 240
#define EE_PRV_PE_SIZE_SECTION_HEADER 40
#define EE_PRV_PE_SIZE_IMPORT_DIRECTORY_ENTRY 20
#define EE_PRV_PE_SIZE_EXPORT_DIRECTORY_ENTRY 40

#define EE_PRV_PE_FILE_OFFSET_IMAGE_SIGNATURE 0x3c

#define EE_PRV_PE_SIGNATURE_IMAGE_FILE 0x4550

#define EE_PRV_PE_MAGIC_OPTIONAL_HEADER 0x10b
#define EE_PRV_PE_MAGIC_OPTIONAL_HEADER_PLUS 0x20b

#define EE_PRV_PE_MACHINE_I386 0x14c
#define EE_PRV_PE_MACHINE_AMD64 0x8664

#define EE_PRV_PE_LIMIT_MAX_IMPORTED_DLLS 16384
#define EE_PRV_PE_LIMIT_MAX_IMPORTED_SYMBOLS_PER_DLL 16384
#define EE_PRV_PE_LIMIT_MAX_EXPORTED_SYMBOLS 16384
#define EE_PRV_PE_LIMIT_MAX_STRING_LENGTH 1024

#endif
